# Generated by Django 3.2.1 on 2021-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(choices=[('cabin', '1'), ('cake', '2'), ('circus', '6'), ('game', '5'), ('safe', '4'), ('submarine', '3'), ('linux', '7'), ('color switch', '8')], max_length=20),
        ),
    ]
