# Generated by Django 3.2.1 on 2021-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(choices=[('1', 'cabin'), ('2', 'cake'), ('6', 'circus'), ('5', 'game'), ('4', 'safe'), ('3', 'submarine'), ('7', 'linux'), ('8', 'color switch'), ('9', 'python'), ('10', 'smart shoe')], max_length=20),
        ),
    ]
